import React, { useState, useEffect, useMemo } from 'react';
import {
  Sparkles,
  Bot,
  RefreshCw,
  TrendingUp,
  AlertOctagon,
  AlertTriangle,
  Zap,
  CheckCircle2,
  Copy,
  Check,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  Filter,
  Layers,
  Cpu,
  ShieldAlert,
  HelpCircle,
  ExternalLink,
  Award,
} from 'lucide-react';
import {
  AuditReport,
  AiAuditInsights,
  AiInsightRecommendation,
  AiPriority,
  AiRecommendationCategory,
} from '../types';
import { copyTextToClipboard } from '../utils/clipboard';

interface AiInsightsSectionProps {
  report: AuditReport;
  onNavigateToTab: (tabId: string) => void;
}

export const AiInsightsSection: React.FC<AiInsightsSectionProps> = ({
  report,
  onNavigateToTab,
}) => {
  const [insights, setInsights] = useState<AiAuditInsights | null>(report.aiInsights || null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [copiedAll, setCopiedAll] = useState<boolean>(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  // Interactive completed checklist state per recommendation step
  const [completedSteps, setCompletedSteps] = useState<Record<string, boolean>>({});

  // Filtering
  const [selectedPriority, setSelectedPriority] = useState<string>('ALL');
  const [selectedCategory, setSelectedCategory] = useState<string>('ALL');

  // Fetch AI Insights from server endpoint (/api/audit/ai-insights)
  const fetchInsights = async (forceRefresh = false) => {
    if (!report || !report.domain) return;
    if (!forceRefresh && insights && insights.domain === report.domain) return;

    setLoading(true);
    setError(null);

    try {
      const response = await fetch('/api/audit/ai-insights', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ report }),
      });

      if (!response.ok) {
        throw new Error(`Server responded with status ${response.status}`);
      }

      const data = await response.json();
      if (data.success && data.insights) {
        setInsights(data.insights);
        // Expand first recommendation by default
        if (data.insights.recommendations?.length > 0) {
          setExpandedId(data.insights.recommendations[0].id);
        }
      } else {
        throw new Error(data.error || 'Failed to parse AI Insights response');
      }
    } catch (err: any) {
      console.error('Failed to fetch AI Insights:', err);
      setError(err.message || 'Unable to generate AI recommendations at this moment.');
    } finally {
      setLoading(false);
    }
  };

  // Automatically generate on initial mount if not present
  useEffect(() => {
    if (!insights || (insights && insights.domain && insights.domain !== report.domain)) {
      fetchInsights(false);
    }
  }, [report.id, report.domain]);

  const toggleStep = (stepKey: string) => {
    setCompletedSteps((prev) => ({
      ...prev,
      [stepKey]: !prev[stepKey],
    }));
  };

  const handleCopyAll = async () => {
    if (!insights) return;
    const text = [
      `=== GEMINI AI SEO & TECHNICAL ROADMAP: ${report.domain} ===`,
      `Generated by: ${insights.modelUsed} (${insights.isAiGenerated ? 'Live Gemini 3.8 Flash' : 'AI Engine'})`,
      `Potential Score Recovery: +${insights.estimatedScoreGain} points`,
      '',
      `STRATEGIC VERDICT:`,
      insights.strategicVerdict,
      '',
      `OVERALL AUDIT HEALTH SUMMARY:`,
      insights.overallHealthSummary,
      '',
      `COMPETITIVE EDGE:`,
      insights.competitiveEdge,
      '',
      `AI SEARCH READINESS (GEO / AEO):`,
      `Status: ${insights.aiSearchReadiness.verdict}`,
      `Citation Potential: ${insights.aiSearchReadiness.citationPotential}`,
      `Key Action: ${insights.aiSearchReadiness.actionItem}`,
      '',
      `PRIORITIZED ACTION RECOMMENDATIONS:`,
      ...insights.recommendations.map(
        (r, i) =>
          `[${r.priority}] #${i + 1}: ${r.title}\nCategory: ${r.category} | Effort: ${r.effort} | Time to Impact: ${r.timeToImpact}\nDiagnosis: ${r.diagnosis}\nRecommendation: ${r.recommendation}\nAction Steps:\n${r.actionSteps.map((s, idx) => `  ${idx + 1}. ${s}`).join('\n')}\n`
      ),
    ].join('\n');

    const success = await copyTextToClipboard(text);
    if (success) {
      setCopiedAll(true);
      setTimeout(() => setCopiedAll(false), 2200);
    }
  };

  const handleCopyRecommendation = async (rec: AiInsightRecommendation) => {
    const text = [
      `[${rec.priority}] ${rec.title}`,
      `Category: ${rec.category} | Effort: ${rec.effort} | Timeline: ${rec.timeToImpact}`,
      `Impact: ${rec.impact}`,
      `Diagnosis: ${rec.diagnosis}`,
      `Action Plan: ${rec.recommendation}`,
      `Checklist:`,
      ...rec.actionSteps.map((s, idx) => `${idx + 1}. ${s}`),
    ].join('\n');

    const success = await copyTextToClipboard(text);
    if (success) {
      setCopiedId(rec.id);
      setTimeout(() => setCopiedId(null), 2000);
    }
  };

  // Map category to application tab for quick jump
  const getTabForCategory = (category: string): string => {
    switch (category) {
      case 'Core Web Vitals':
        return 'technical';
      case 'Technical & Crawl':
        return 'architecture';
      case 'On-Page & Content':
        return 'on-page';
      case 'AI & AEO':
        return 'ai_readiness';
      case 'Authority & Schema':
        return 'schema';
      default:
        return 'overview';
    }
  };

  // Filter recommendations
  const filteredRecommendations = useMemo(() => {
    if (!insights?.recommendations) return [];
    return insights.recommendations.filter((rec) => {
      const matchPriority =
        selectedPriority === 'ALL' ||
        rec.priority.toLowerCase().startsWith(selectedPriority.toLowerCase());
      const matchCategory =
        selectedCategory === 'ALL' ||
        rec.category.toLowerCase().includes(selectedCategory.toLowerCase());
      return matchPriority && matchCategory;
    });
  }, [insights, selectedPriority, selectedCategory]);

  const priorityCounts = useMemo(() => {
    const counts: Record<string, number> = { ALL: insights?.recommendations?.length || 0, P0: 0, P1: 0, P2: 0, P3: 0 };
    insights?.recommendations?.forEach((r) => {
      if (r.priority.startsWith('P0')) counts.P0 = (counts.P0 || 0) + 1;
      else if (r.priority.startsWith('P1')) counts.P1 = (counts.P1 || 0) + 1;
      else if (r.priority.startsWith('P2')) counts.P2 = (counts.P2 || 0) + 1;
      else if (r.priority.startsWith('P3')) counts.P3 = (counts.P3 || 0) + 1;
    });
    return counts;
  }, [insights]);

  return (
    <section
      id="ai-insights-section"
      aria-label="Gemini AI Audit Insights"
      className="bg-white border border-slate-200 rounded-3xl p-5 sm:p-7 shadow-xs space-y-6"
    >
      {/* Header Banner with Gemini Badge and Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 pb-5">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-purple-600 via-indigo-600 to-blue-600 flex items-center justify-center text-white shadow-sm shrink-0">
            <Sparkles className="w-5 h-5 animate-pulse" />
          </div>
          <div>
            <div className="flex flex-wrap items-center gap-2">
              <h2 className="text-base sm:text-lg font-black text-slate-900 tracking-tight">
                AI Strategic Insights &amp; Prioritized Roadmap
              </h2>
              <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-purple-100 text-purple-800 border border-purple-200">
                <Bot className="w-3 h-3 text-purple-600" />
                <span>{insights?.modelUsed ? insights.modelUsed : 'Gemini 3.8 Flash'}</span>
              </span>
              {insights?.isAiGenerated && (
                <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800 border border-emerald-200">
                  Live Gemini Reasoning
                </span>
              )}
            </div>
            <p className="text-xs text-slate-500 mt-1">
              Automated multi-vector diagnostic analyzing Core Web Vitals, architecture, content gaps, and Generative Engine Optimization (GEO).
            </p>
          </div>
        </div>

        {/* Action Controls: Refresh & Copy */}
        <div className="flex items-center gap-2 shrink-0">
          <button
            type="button"
            id="regenerate-ai-insights-btn"
            onClick={() => fetchInsights(true)}
            disabled={loading}
            className="px-3.5 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer disabled:opacity-60 disabled:cursor-not-allowed"
            title="Re-run Gemini AI analysis on the current audit data"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin text-purple-600' : ''}`} />
            <span>{loading ? 'Analyzing...' : 'Regenerate'}</span>
          </button>

          <button
            type="button"
            id="copy-ai-insights-btn"
            onClick={handleCopyAll}
            disabled={!insights}
            className="px-3.5 py-2 rounded-xl bg-purple-50 hover:bg-purple-100 text-purple-700 border border-purple-200 text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer disabled:opacity-50"
            title="Copy complete AI recommendations report to clipboard"
          >
            {copiedAll ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-600" />
                <span className="text-emerald-700">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy All</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Loading State Spinner */}
      {loading && (
        <div className="py-12 px-6 flex flex-col items-center justify-center text-center space-y-3 bg-purple-50/40 rounded-2xl border border-purple-100">
          <div className="w-10 h-10 rounded-full border-3 border-purple-200 border-t-purple-600 animate-spin" />
          <h3 className="text-sm font-bold text-slate-800">
            Synthesizing Audit Metrics with Gemini 3.8 Flash...
          </h3>
          <p className="text-xs text-slate-500 max-w-md">
            Analyzing {report.crawledPages?.length || 1} pages, evaluating Core Web Vitals thresholds, verifying robots.txt directives, and prioritizing immediate ROI engineering actions.
          </p>
        </div>
      )}

      {/* Error Banner */}
      {error && !loading && (
        <div className="p-4 rounded-2xl bg-rose-50 border border-rose-200 flex items-start gap-3 text-xs text-rose-800">
          <AlertOctagon className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
          <div className="flex-1">
            <span className="font-bold">Insight generation issue:</span> {error}
          </div>
          <button
            type="button"
            onClick={() => fetchInsights(true)}
            className="px-2.5 py-1 bg-rose-200 hover:bg-rose-300 rounded-lg font-bold text-[11px] cursor-pointer"
          >
            Retry
          </button>
        </div>
      )}

      {/* Content Body when loaded */}
      {insights && !loading && (
        <div className="space-y-6">
          {/* Temporary Demand Peak Info Notice */}
          {insights.demandPeakNotice && (
            <div className="px-4 py-3 rounded-2xl bg-amber-50/90 border border-amber-200/80 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs text-amber-900 shadow-2xs">
              <div className="flex items-center gap-2.5">
                <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
                <span className="font-medium">{insights.demandPeakNotice}</span>
              </div>
              <button
                type="button"
                onClick={() => fetchInsights(true)}
                className="px-3 py-1.5 bg-amber-200/90 hover:bg-amber-300 rounded-xl text-amber-950 font-bold text-xs shrink-0 cursor-pointer transition-colors"
              >
                Retry Live Gemini
              </button>
            </div>
          )}

          {/* Top High-Impact Diagnostic Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            
            {/* 1. Strategic Verdict */}
            <div className="md:col-span-2 bg-gradient-to-br from-slate-900 via-slate-850 to-indigo-950 text-white rounded-2xl p-5 sm:p-6 shadow-sm flex flex-col justify-between space-y-4">
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="px-2.5 py-0.5 rounded-full text-[10px] font-extrabold uppercase tracking-wider bg-purple-500/25 text-purple-300 border border-purple-400/30">
                      Executive Diagnosis
                    </span>
                    <span className="text-[11px] text-slate-300 font-mono">
                      Target: {report.domain}
                    </span>
                  </div>
                  <div className="flex items-center gap-1.5 px-3 py-1 rounded-xl bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 text-xs font-black">
                    <TrendingUp className="w-3.5 h-3.5" />
                    <span>+{insights.estimatedScoreGain} pts Recovery Potential</span>
                  </div>
                </div>

                <h3 className="text-sm sm:text-base font-bold text-white leading-snug">
                  {insights.strategicVerdict}
                </h3>

                <p className="text-xs text-slate-300 leading-relaxed pt-1">
                  {insights.overallHealthSummary}
                </p>
              </div>

              {/* Competitive Differentiator Pill */}
              <div className="pt-3 border-t border-white/10 flex items-start gap-2 text-xs text-indigo-200">
                <Award className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                <span>
                  <strong className="text-white font-semibold">Competitive Edge:</strong>{' '}
                  {insights.competitiveEdge}
                </span>
              </div>
            </div>

            {/* 2. Generative Engine Optimization (GEO) & AI Search Callout */}
            <div className="bg-gradient-to-br from-purple-50 via-indigo-50/50 to-white border border-purple-200/80 rounded-2xl p-5 shadow-2xs flex flex-col justify-between space-y-3">
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="p-1.5 rounded-lg bg-purple-100 text-purple-700">
                      <Bot className="w-4 h-4" />
                    </div>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-purple-900">
                      AI Search (GEO / AEO)
                    </h4>
                  </div>
                  <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-purple-200 text-purple-800">
                    Google AI Overviews
                  </span>
                </div>

                <div className="text-xs font-bold text-slate-900 pt-1">
                  {insights.aiSearchReadiness.verdict}
                </div>

                <p className="text-xs text-slate-600 leading-relaxed">
                  {insights.aiSearchReadiness.citationPotential}
                </p>
              </div>

              <div className="pt-3 border-t border-purple-100 text-xs space-y-1">
                <div className="font-semibold text-purple-900 text-[11px] flex items-center gap-1">
                  <Zap className="w-3.5 h-3.5 text-amber-500" />
                  <span>Primary AEO Action:</span>
                </div>
                <p className="text-slate-700 text-[11px] leading-relaxed">
                  {insights.aiSearchReadiness.actionItem}
                </p>
              </div>
            </div>

          </div>

          {/* Interactive Filter Toolbar */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-3 rounded-2xl bg-slate-50 border border-slate-200/80">
            <div className="flex flex-wrap items-center gap-1.5">
              <span className="text-xs font-bold text-slate-600 flex items-center gap-1 mr-1">
                <Filter className="w-3.5 h-3.5 text-slate-400" />
                <span>Priority:</span>
              </span>

              {(['ALL', 'P0', 'P1', 'P2', 'P3'] as const).map((p) => {
                const count = priorityCounts[p] || 0;
                const isSelected = selectedPriority === p;
                const label =
                  p === 'ALL'
                    ? `All (${count})`
                    : p === 'P0'
                    ? `P0 Critical (${count})`
                    : p === 'P1'
                    ? `P1 High (${count})`
                    : p === 'P2'
                    ? `P2 Medium (${count})`
                    : `P3 Low (${count})`;

                return (
                  <button
                    key={p}
                    type="button"
                    onClick={() => setSelectedPriority(p)}
                    className={`px-2.5 py-1 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                      isSelected
                        ? p === 'P0'
                          ? 'bg-rose-600 text-white shadow-xs'
                          : p === 'P1'
                          ? 'bg-amber-500 text-white shadow-xs'
                          : p === 'P2'
                          ? 'bg-blue-600 text-white shadow-xs'
                          : 'bg-slate-800 text-white shadow-xs'
                        : 'bg-white hover:bg-slate-200 text-slate-600 border border-slate-200'
                    }`}
                  >
                    {label}
                  </button>
                );
              })}
            </div>

            {/* Category Select Dropdown */}
            <div className="flex items-center gap-2">
              <span className="text-xs font-medium text-slate-500 hidden sm:inline">Category:</span>
              <select
                aria-label="Filter recommendations by category"
                value={selectedCategory}
                onChange={(e) => setSelectedCategory(e.target.value)}
                className="bg-white border border-slate-300 rounded-xl px-2.5 py-1 text-xs font-bold text-slate-700 outline-none focus:border-purple-500 cursor-pointer"
              >
                <option value="ALL">All Categories</option>
                <option value="Core Web Vitals">Core Web Vitals</option>
                <option value="Technical & Crawl">Technical &amp; Crawl</option>
                <option value="On-Page & Content">On-Page &amp; Content</option>
                <option value="AI & AEO">AI &amp; AEO (Generative Search)</option>
                <option value="Authority & Schema">Authority &amp; Schema</option>
              </select>
            </div>
          </div>

          {/* Filtered Recommendations List */}
          <div className="space-y-3.5">
            {filteredRecommendations.length === 0 ? (
              <div className="p-8 text-center text-slate-500 text-xs bg-slate-50 rounded-2xl border border-slate-200">
                No recommendations match the selected priority or category filters.
              </div>
            ) : (
              filteredRecommendations.map((rec) => {
                const isExpanded = expandedId === rec.id;
                const isP0 = rec.priority.startsWith('P0');
                const isP1 = rec.priority.startsWith('P1');
                const isP2 = rec.priority.startsWith('P2');
                const priorityBadgeClass = isP0
                  ? 'bg-rose-100 text-rose-800 border-rose-200'
                  : isP1
                  ? 'bg-amber-100 text-amber-800 border-amber-200'
                  : isP2
                  ? 'bg-blue-100 text-blue-800 border-blue-200'
                  : 'bg-slate-100 text-slate-700 border-slate-200';

                const targetTab = getTabForCategory(rec.category);

                return (
                  <div
                    key={rec.id}
                    className={`border rounded-2xl transition-all duration-200 ${
                      isExpanded
                        ? 'border-purple-300 bg-white shadow-md ring-2 ring-purple-100'
                        : 'border-slate-200 bg-white hover:border-slate-300 hover:shadow-xs'
                    }`}
                  >
                    {/* Collapsible Card Header */}
                    <div
                      onClick={() => setExpandedId(isExpanded ? null : rec.id)}
                      className="p-4 sm:p-5 flex items-start justify-between gap-3 cursor-pointer select-none"
                    >
                      <div className="space-y-2 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <span
                            className={`px-2.5 py-0.5 rounded-md text-[11px] font-black uppercase tracking-wider border flex items-center gap-1 ${priorityBadgeClass}`}
                          >
                            {isP0 && <AlertOctagon className="w-3 h-3 text-rose-600" />}
                            {isP1 && <AlertTriangle className="w-3 h-3 text-amber-600" />}
                            {isP2 && <Zap className="w-3 h-3 text-blue-600" />}
                            <span>{rec.priority}</span>
                          </span>

                          <span className="px-2 py-0.5 rounded-md text-[11px] font-bold bg-slate-100 text-slate-700 border border-slate-200">
                            {rec.category}
                          </span>

                          <span className="text-[11px] font-semibold text-slate-500 flex items-center gap-1">
                            <span>Effort:</span>
                            <span className="font-bold text-slate-800">{rec.effort}</span>
                          </span>

                          <span className="text-[11px] text-slate-400">&bull;</span>

                          <span className="text-[11px] font-semibold text-slate-500 flex items-center gap-1">
                            <span>Timeline:</span>
                            <span className="font-bold text-slate-800">{rec.timeToImpact}</span>
                          </span>
                        </div>

                        <h4 className="text-sm sm:text-base font-bold text-slate-900">
                          {rec.title}
                        </h4>

                        <p className="text-xs text-slate-600 line-clamp-2">
                          <strong className="text-slate-800 font-semibold">Impact:</strong> {rec.impact}
                        </p>
                      </div>

                      {/* Expand / Collapse Chevron */}
                      <div className="flex items-center gap-2 shrink-0 pt-1">
                        <button
                          type="button"
                          className="p-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-600 transition-colors"
                          aria-label={isExpanded ? 'Collapse recommendation' : 'Expand recommendation'}
                        >
                          {isExpanded ? (
                            <ChevronUp className="w-4 h-4" />
                          ) : (
                            <ChevronDown className="w-4 h-4" />
                          )}
                        </button>
                      </div>
                    </div>

                    {/* Expandable Step-by-Step Action Plan */}
                    {isExpanded && (
                      <div className="px-4 sm:px-5 pb-5 pt-1 border-t border-slate-100 space-y-4 text-xs">
                        {/* Diagnosis & Prescriptive Fix */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2">
                          <div className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 space-y-1">
                            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500">
                              Diagnostic Finding:
                            </span>
                            <p className="text-slate-700 leading-relaxed font-medium">
                              {rec.diagnosis}
                            </p>
                          </div>

                          <div className="p-3 rounded-xl bg-purple-50/60 border border-purple-200/80 space-y-1">
                            <span className="text-[11px] font-bold uppercase tracking-wider text-purple-700">
                              Architectural Solution:
                            </span>
                            <p className="text-purple-950 leading-relaxed font-medium">
                              {rec.recommendation}
                            </p>
                          </div>
                        </div>

                        {/* Implementation Checklist */}
                        <div className="space-y-2 pt-1">
                          <div className="flex items-center justify-between">
                            <span className="text-xs font-bold text-slate-800">
                              Developer Implementation Checklist:
                            </span>
                            {rec.affectedComponent && (
                              <span className="text-[11px] font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded border border-slate-200 truncate max-w-xs">
                                Asset: {rec.affectedComponent}
                              </span>
                            )}
                          </div>

                          <div className="space-y-1.5">
                            {rec.actionSteps.map((step, idx) => {
                              const stepKey = `${rec.id}_step_${idx}`;
                              const isChecked = Boolean(completedSteps[stepKey]);
                              return (
                                <div
                                  key={idx}
                                  onClick={() => toggleStep(stepKey)}
                                  className={`p-2.5 rounded-xl border flex items-start gap-2.5 transition-all cursor-pointer select-none ${
                                    isChecked
                                      ? 'bg-emerald-50/50 border-emerald-200 text-emerald-900'
                                      : 'bg-slate-50 border-slate-200 text-slate-800 hover:bg-slate-100/70'
                                  }`}
                                >
                                  <input
                                    type="checkbox"
                                    checked={isChecked}
                                    onChange={() => {}} // handled by parent div
                                    className="mt-0.5 rounded border-slate-300 text-purple-600 focus:ring-purple-500 cursor-pointer"
                                  />
                                  <span className={`text-xs ${isChecked ? 'line-through text-slate-400' : ''}`}>
                                    <strong className="font-semibold">{idx + 1}.</strong> {step}
                                  </span>
                                </div>
                              );
                            })}
                          </div>
                        </div>

                        {/* Bottom Action Footer for Card */}
                        <div className="pt-3 border-t border-slate-100 flex flex-wrap items-center justify-between gap-3">
                          <button
                            type="button"
                            onClick={() => handleCopyRecommendation(rec)}
                            className="px-3 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer"
                          >
                            {copiedId === rec.id ? (
                              <>
                                <Check className="w-3.5 h-3.5 text-emerald-600" />
                                <span className="text-emerald-700 font-bold">Action Plan Copied</span>
                              </>
                            ) : (
                              <>
                                <Copy className="w-3.5 h-3.5 text-slate-500" />
                                <span>Copy Action Plan</span>
                              </>
                            )}
                          </button>

                          <button
                            type="button"
                            onClick={() => onNavigateToTab(targetTab)}
                            className="px-3.5 py-1.5 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs font-bold flex items-center gap-1.5 transition-all shadow-xs cursor-pointer"
                          >
                            <span>Inspect in {rec.category}</span>
                            <ArrowRight className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })
            )}
          </div>
        </div>
      )}
    </section>
  );
};
