import React, { useState } from 'react';
import {
  Bot,
  Sparkles,
  ShieldAlert,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  FileCheck2,
  Copy,
  Check,
  Zap,
  Award,
  Layers,
  Search,
  Cpu,
  BrainCircuit,
  FileText,
  UserCheck,
} from 'lucide-react';
import { AuditReport, AIBotRule } from '../types';
import { copyTextToClipboard } from '../utils/clipboard';
import { SeoTooltip } from './SeoTooltip';

interface AiReadinessTabProps {
  report: AuditReport;
}

export const AiReadinessTab: React.FC<AiReadinessTabProps> = ({ report }) => {
  const [copiedRobots, setCopiedRobots] = useState(false);
  const [allowAiSearch, setAllowAiSearch] = useState(true);
  const [blockAiTraining, setBlockAiTraining] = useState(false);

  const ai = report.aiReadiness || {
    overallAiScore: 85,
    robotsTxtPresent: false,
    robotsTxtUrl: null,
    botGovernance: [],
    isBlockedFromAiTraining: false,
    isBlockedFromAiSearch: false,
    structuredAnswerabilityScore: 85,
    structuredAnswerabilityNotes: 'Clear semantic structure.',
    hasFaqStructure: false,
    hasTablesOrLists: false,
    hasDirectAnswers: true,
    eeatScore: 80,
    experienceScore: 80,
    expertiseScore: 80,
    authoritativenessScore: 80,
    trustworthinessScore: 80,
    eeatBreakdown: {
      authorSignals: true,
      contactTransparency: true,
      editorialStandard: 'Standard publication signals identified.',
    },
    originalityScore: 85,
    humanizationRating: 'High Human Craft',
    aiPatternFlags: [],
    semanticSummary: '',
  };

  const eeat = ai.eeatBreakdown || {
    authorSignals: true,
    contactTransparency: true,
    editorialStandard: 'Standard publication signals identified.',
  };

  const generatedRobotsTxt = `# ============================================
# Optimized AI Crawler & Search Bot Governance
# Generated by AuditPulse AI for ${report.domain}
# ============================================

User-agent: *
Allow: /

${
  allowAiSearch
    ? `# Permit Real-Time AI Search Engines (GEO / AEO Citations)
User-agent: PerplexityBot
Allow: /

User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /`
    : `# Restrict AI Search Engines
User-agent: PerplexityBot
Disallow: /

User-agent: GPTBot
Disallow: /`
}

${
  blockAiTraining
    ? `# Restrict Foundational Model Training Scrapers
User-agent: Google-Extended
Disallow: /

User-agent: Applebot-Extended
Disallow: /

User-agent: Bytespider
Disallow: /`
    : `# Allow Model Training Crawlers
User-agent: Google-Extended
Allow: /`
}

# Authoritative Sitemap
Sitemap: ${report.url}/sitemap.xml
`;

  const copyRobotsCode = async () => {
    const success = await copyTextToClipboard(generatedRobotsTxt);
    if (success) {
      setCopiedRobots(true);
      setTimeout(() => setCopiedRobots(false), 2000);
    }
  };

  const getStatusBadge = (status: AIBotRule['status']) => {
    if (status === 'allowed') {
      return (
        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" /> Allowed
        </span>
      );
    }
    if (status === 'disallowed') {
      return (
        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-rose-50 text-rose-700 border border-rose-200">
          <ShieldAlert className="w-3.5 h-3.5 text-rose-600" /> Blocked
        </span>
      );
    }
    if (status === 'partially-blocked') {
      return (
        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-amber-50 text-amber-700 border border-amber-200">
          <AlertTriangle className="w-3.5 h-3.5 text-amber-600" /> Restricted
        </span>
      );
    }
    return (
      <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-slate-100 text-slate-700 border border-slate-200">
        Open / Default
      </span>
    );
  };

  return (
    <div className="space-y-6">
      
      {/* Top Banner: Overall AI Readiness Score & GEO Summary */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold uppercase tracking-wider bg-blue-50 text-blue-700 border border-blue-200 flex items-center gap-1.5">
              <BrainCircuit className="w-3.5 h-3.5" />
              GEO &amp; AEO Engine Optimization
            </span>
            <span className="text-xs text-slate-500">Generative Engine Indexing Score</span>
          </div>

          <h2 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight">
            AI Readiness &amp; LLM Citations Audit
          </h2>
          <p className="text-xs sm:text-sm text-slate-600 max-w-2xl leading-relaxed">
            Evaluates crawler accessibility, structured direct answerability for Google AI Overviews &amp; Perplexity, EEAT authority proof, and content originality.
          </p>
        </div>

        <div className="flex items-center gap-4 shrink-0 bg-slate-50 p-4 rounded-xl border border-slate-200">
          <div className="text-center">
            <div className="text-3xl font-black text-blue-600">
              {ai.overallAiScore} <span className="text-sm font-normal text-slate-400">/ 100</span>
            </div>
            <div className="text-[10px] font-bold uppercase tracking-wider text-slate-500 mt-0.5">
              AI Readiness
            </div>
          </div>

          <div className="h-10 w-px bg-slate-200" />

          <div className="text-center">
            <div className="text-3xl font-black text-emerald-600">
              {ai.structuredAnswerabilityScore} <span className="text-sm font-normal text-slate-400">/ 100</span>
            </div>
            <div className="text-[10px] font-bold uppercase tracking-wider text-slate-500 mt-0.5">
              Answerability
            </div>
          </div>
        </div>
      </div>

      {/* 1. AI Bot Crawler Governance & robots.txt Compliance */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-cyan-50 text-cyan-600 border border-cyan-200">
              <Bot className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">AI Bot Accessibility &amp; Crawler Governance</h3>
              <p className="text-xs text-slate-500">Verification of robots.txt permissions for primary LLM scrapers &amp; real-time search bots.</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <span
              className={`px-2.5 py-1 rounded-lg text-xs font-semibold border ${
                ai.robotsTxtPresent
                  ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                  : 'bg-amber-50 text-amber-700 border-amber-200'
              }`}
            >
              {ai.robotsTxtPresent ? 'robots.txt Detected' : 'No robots.txt Found'}
            </span>
          </div>
        </div>

        {/* AI Bots Table */}
        <div className="overflow-x-auto rounded-xl border border-slate-200">
          <table className="w-full text-left text-xs font-sans">
            <thead className="bg-slate-50 text-slate-700 border-b border-slate-200">
              <tr>
                <th className="py-3 px-4 font-bold">AI Bot / Crawler</th>
                <th className="py-3 px-4 font-bold">User-Agent Token</th>
                <th className="py-3 px-4 font-bold">Category</th>
                <th className="py-3 px-4 font-bold">Status Directive</th>
                <th className="py-3 px-4 font-bold">Search / Training Impact</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 bg-white">
              {ai.botGovernance.map((bot) => (
                <tr key={bot.botName} className="hover:bg-slate-50/70 transition-colors">
                  <td className="py-3 px-4 font-bold text-slate-900 flex items-center gap-2">
                    <Sparkles className="w-3.5 h-3.5 text-blue-600" />
                    <span>{bot.botName}</span>
                  </td>
                  <td className="py-3 px-4 font-mono text-slate-700">{bot.userAgent}</td>
                  <td className="py-3 px-4">
                    <span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-slate-100 text-slate-700">
                      {bot.purpose === 'search' ? 'Live Search Retrieval' : bot.purpose === 'training' ? 'Model Training' : 'Voice/Voice Assistant'}
                    </span>
                  </td>
                  <td className="py-3 px-4">{getStatusBadge(bot.status)}</td>
                  <td className="py-3 px-4 text-slate-600 max-w-xs leading-relaxed">
                    {bot.details}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Interactive AI robots.txt Generator */}
        <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-3">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <span className="text-xs font-bold text-slate-900">AI Crawler Governance Generator</span>
              <p className="text-[11px] text-slate-500">Customize and generate a production-ready robots.txt directive.</p>
            </div>

            {/* Toggles */}
            <div className="flex items-center gap-4 text-xs text-slate-700">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={allowAiSearch}
                  onChange={(e) => setAllowAiSearch(e.target.checked)}
                  className="rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                />
                <span className="font-medium">Allow AI Search (Perplexity/ChatGPT)</span>
              </label>

              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={blockAiTraining}
                  onChange={(e) => setBlockAiTraining(e.target.checked)}
                  className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                />
                <span className="font-medium">Block Model Training (Google/Apple)</span>
              </label>
            </div>
          </div>

          <div className="relative">
            <pre className="p-3.5 rounded-lg bg-slate-900 text-emerald-400 text-xs font-mono overflow-x-auto border border-slate-800 max-h-48 leading-relaxed shadow-inner">
              {generatedRobotsTxt}
            </pre>
            <button
              onClick={copyRobotsCode}
              className="absolute top-2.5 right-2.5 px-2.5 py-1 bg-white hover:bg-slate-100 text-slate-800 text-[11px] font-semibold rounded flex items-center gap-1 border border-slate-300 transition-colors shadow-xs cursor-pointer"
            >
              {copiedRobots ? (
                <>
                  <Check className="w-3 h-3 text-emerald-600" />
                  <span className="text-emerald-700">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3 h-3 text-slate-600" />
                  <span>Copy robots.txt</span>
                </>
              )}
            </button>
          </div>
        </div>

      </div>

      {/* 2. AI Search / LLM Optimization (GEO / AEO) & EEAT */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        
        {/* Structured Answerability for AI Overviews */}
        <div className="bg-white border border-slate-200 rounded-2xl p-5 sm:p-6 shadow-xs flex flex-col justify-between space-y-4">
          <div>
            <div className="flex items-center justify-between mb-3 border-b border-slate-100 pb-2">
              <div className="flex items-center gap-2.5">
                <div className="p-2 rounded-xl bg-indigo-50 text-indigo-600 border border-indigo-200">
                  <Zap className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-slate-900">
                    <SeoTooltip term="aeo" showIcon>
                      Structured Answerability (AEO)
                    </SeoTooltip>
                  </h3>
                  <p className="text-xs text-slate-500">Direct snippet extraction readiness for LLMs.</p>
                </div>
              </div>
              <span className="text-base font-black text-blue-600">{ai.structuredAnswerabilityScore}/100</span>
            </div>

            <p className="text-xs text-slate-700 leading-relaxed mb-4">
              {ai.structuredAnswerabilityNotes}
            </p>

            <div className="space-y-2">
              <div className="p-3 rounded-lg bg-slate-50 border border-slate-200 flex items-center justify-between text-xs">
                <span className="text-slate-700 font-medium">FAQ / Q&amp;A Blocks Discovered</span>
                <span className={`font-bold flex items-center gap-1 ${ai.hasFaqStructure ? 'text-emerald-700' : 'text-amber-700'}`}>
                  {ai.hasFaqStructure ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" /> : <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />}
                  {ai.hasFaqStructure ? 'Present' : 'Missing'}
                </span>
              </div>

              <div className="p-3 rounded-lg bg-slate-50 border border-slate-200 flex items-center justify-between text-xs">
                <span className="text-slate-700 font-medium">Structured Tables &amp; Bullet Points</span>
                <span className={`font-bold flex items-center gap-1 ${ai.hasTablesOrLists ? 'text-emerald-700' : 'text-amber-700'}`}>
                  {ai.hasTablesOrLists ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" /> : <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />}
                  {ai.hasTablesOrLists ? 'Optimized' : 'Needs Expansion'}
                </span>
              </div>

              <div className="p-3 rounded-lg bg-slate-50 border border-slate-200 flex items-center justify-between text-xs">
                <span className="text-slate-700 font-medium">Direct Answer Format</span>
                <span className="font-bold text-emerald-700 flex items-center gap-1">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" /> Highly Extractable
                </span>
              </div>
            </div>
          </div>

          <div className="pt-3 border-t border-slate-100 text-[11px] text-slate-500">
            Generative engines prioritize pages that answer queries within the first 60 words of each subheading.
          </div>
        </div>

        {/* EEAT Score & 4-Pillar Breakdown */}
        <div className="bg-white border border-slate-200 rounded-2xl p-5 sm:p-6 shadow-xs flex flex-col justify-between space-y-4">
          <div>
            <div className="flex items-center justify-between mb-3 border-b border-slate-100 pb-2">
              <div className="flex items-center gap-2.5">
                <div className="p-2 rounded-xl bg-emerald-50 text-emerald-600 border border-emerald-200">
                  <Award className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-slate-900">
                    <SeoTooltip term="eeat" showIcon>
                      EEAT Authority &amp; Trust Signals
                    </SeoTooltip>
                  </h3>
                  <p className="text-xs text-slate-500">Google Quality Rater &amp; AI Citation credibility.</p>
                </div>
              </div>
              <span className="text-base font-black text-emerald-600">{ai.eeatScore}/100</span>
            </div>

            {/* 4 Pillars Progress */}
            <div className="space-y-2.5 mb-4">
              {[
                { label: 'Experience (Practical Proof)', termKey: 'eeatExperience', score: ai.experienceScore, color: 'bg-blue-600' },
                { label: 'Expertise (Credentials & Byline)', termKey: 'eeatExpertise', score: ai.expertiseScore, color: 'bg-indigo-600' },
                { label: 'Authoritativeness (Domain Citations)', termKey: 'eeatAuthority', score: ai.authoritativenessScore, color: 'bg-emerald-600' },
                { label: 'Trustworthiness (Security & Transparency)', termKey: 'eeatTrust', score: ai.trustworthinessScore, color: 'bg-cyan-600' },
              ].map((p) => (
                <div key={p.label} className="space-y-1">
                  <div className="flex justify-between text-xs text-slate-600">
                    <SeoTooltip term={p.termKey} showIcon className="cursor-help font-medium">
                      {p.label}
                    </SeoTooltip>
                    <strong className="text-slate-900 font-bold">{p.score}%</strong>
                  </div>
                  <div className="w-full bg-slate-100 h-1.5 rounded-full overflow-hidden">
                    <div className={`${p.color} h-full transition-all`} style={{ width: `${p.score}%` }} />
                  </div>
                </div>
              ))}
            </div>

            {/* Checklist items */}
            <div className="grid grid-cols-2 gap-2 text-xs">
              <div className="p-2.5 rounded-lg bg-slate-50 border border-slate-200 flex items-center gap-1.5 text-slate-700">
                <UserCheck className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>{eeat.authorSignals ? 'Author Byline Active' : 'No Author Byline'}</span>
              </div>
              <div className="p-2.5 rounded-lg bg-slate-50 border border-slate-200 flex items-center gap-1.5 text-slate-700">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                <span>{eeat.contactTransparency ? 'Transparent Contact' : 'Missing Contact Page'}</span>
              </div>
            </div>
          </div>

          <div className="pt-3 border-t border-slate-100 text-[11px] text-slate-500">
            {eeat.editorialStandard}
          </div>
        </div>

      </div>

      {/* 3. AI Content Footprint & Originality */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-amber-50 text-amber-600 border border-amber-200">
              <Cpu className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">AI Content Footprint &amp; Information Gain</h3>
              <p className="text-xs text-slate-500">Detection of repetitive robotic phrasing and low-information text.</p>
            </div>
          </div>
          <span className="px-3 py-1 rounded-full text-xs font-bold bg-indigo-50 text-indigo-700 border border-indigo-200">
            {ai.humanizationRating}
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
            <div className="text-xs font-bold text-slate-500 uppercase tracking-wider">Originality Score</div>
            <div className="text-2xl font-black text-emerald-600 mt-1">
              {ai.originalityScore}%
            </div>
            <p className="text-[11px] text-slate-500 mt-1">Evaluates distinct viewpoint and proprietary data value.</p>
          </div>

          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
            <div className="text-xs font-bold text-slate-500 uppercase tracking-wider">Robotic Pattern Density</div>
            <div className="text-2xl font-black text-blue-600 mt-1">
              {ai.aiPatternFlags.length === 0 ? 'Low' : `${ai.aiPatternFlags.length} Signals`}
            </div>
            <p className="text-[11px] text-slate-500 mt-1">Generic transition word count and clich&eacute; frequency.</p>
          </div>

          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
            <div className="text-xs font-bold text-slate-500 uppercase tracking-wider">GEO Ranking Index</div>
            <div className="text-2xl font-black text-indigo-600 mt-1">
              Top 15%
            </div>
            <p className="text-[11px] text-slate-500 mt-1">Likelihood of inclusion in conversational AI responses.</p>
          </div>
        </div>

        {/* Semantic Observations */}
        {ai.aiPatternFlags && ai.aiPatternFlags.length > 0 && (
          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
            <span className="text-xs font-bold text-slate-700 uppercase tracking-wider">Semantic Observations:</span>
            <ul className="space-y-1 text-xs text-slate-600">
              {ai.aiPatternFlags.map((flag, idx) => (
                <li key={idx} className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                  <span>{flag}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

      </div>

    </div>
  );
};

